### ISSUE TITLE
The app doesn't work yet

### ISSUE THREAD

**Issue by MarcusAdriano** [MarcusAdriano/CallBlockerProject#1]
There are any things to do, in first time this app need works, in others words, it's need block calls from a "black list". The "black list" works, but when app receive a call, it's broke. Bellow there is a TO DO list:

1. Block calls;
2. Improve UI with Fragments;
3. Implements SMS blocker;
4. Add "pick a contact" implementation when user add new contact on black list.

**Comment by dougouk** [comment]
Just a little note: you should probably break down the 4 tasks into 4 separate issues

**Comment by MarcusAdriano** [comment]
Hi, @dougouk I'll do this.
