### ISSUE TITLE
Travis CI don't works

### ISSUE THREAD

**Issue by MarcusAdriano** [MarcusAdriano/CallBlockerProject#3]
Changes in travis' file apparently don't produce anyone effect when Travis build repository. 
Disabled lint in build.gradle in app module too don't solve.

**Comment by rivermont** [comment]
It looks like you need to accept the Android SDK Built-Tools License. [Source](https://travis-ci.org/MarcusAdriano/CallBlockerProject#L2080)

    A problem occurred configuring project ':CallBlocker'.
    > You have not accepted the license agreements of the following SDK components:
      [Android SDK Build-Tools 25.0.3].
      Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
      Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

**Comment by MarcusAdriano** [comment]
Thanks @rivermont, add license solved it.
